#!/usr/bin/env python3
"""Generate COUNTRY_LOOKUP entries from Unicode CLDR zh-Hant → en territory names.

Optional: fetch distinct Immich EXIF countries via IMMICH_BASE_URL + IMMICH_API_KEY
to emit runtime alias hints in country-lookup-immich-aliases.json.

Usage:
  python3 scripts/generate-country-lookup.py
  IMMICH_BASE_URL=https://immich.3q.fi IMMICH_API_KEY=... python3 scripts/generate-country-lookup.py
"""

from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_TS = ROOT / "src/line-bot/data/country-lookup.generated.ts"
OUT_ALIASES = ROOT / "src/line-bot/data/country-lookup-immich-aliases.json"

CLDR_BASE = (
    "https://raw.githubusercontent.com/unicode-org/cldr-json/main/"
    "cldr-json/cldr-localenames-full/main"
)

# Immich reverse-geocoding names that differ from CLDR English short names.
IMMICH_COUNTRY_BY_CODE: dict[str, str] = {
    "TW": "Taiwan, Province of China",
    "US": "United States",
    "GB": "United Kingdom",
    "KR": "South Korea",
    "RU": "Russia",
    "VN": "Vietnam",
    "IR": "Iran",
    "SY": "Syria",
    "VE": "Venezuela",
    "BO": "Bolivia",
    "TZ": "Tanzania",
    "LA": "Laos",
    "MD": "Moldova",
    "FM": "Micronesia",
}


def fetch_json(url: str) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": "immich-apps-country-lookup/1.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.load(resp)


def escape_regex(text: str) -> str:
    return re.sub(r"([\\.*+?^${}()|[\]])", r"\\\1", text)


def territory_entries() -> list[tuple[str, str]]:
    zh_url = f"{CLDR_BASE}/zh-Hant/territories.json"
    en_url = f"{CLDR_BASE}/en/territories.json"
    zh_data = fetch_json(zh_url)["main"]["zh-Hant"]["localeDisplayNames"]["territories"]
    en_data = fetch_json(en_url)["main"]["en"]["localeDisplayNames"]["territories"]

    rows: list[tuple[str, str]] = []
    for code, zh_name in zh_data.items():
        if not re.fullmatch(r"[A-Z]{2}", code):
            continue
        if zh_name in ("世界", "Unknown Region"):
            continue
        en_name = en_data.get(code)
        if not en_name:
            continue
        immich_name = IMMICH_COUNTRY_BY_CODE.get(code, en_name)
        rows.append((zh_name, immich_name))

    rows.sort(key=lambda row: (-len(row[0]), row[0]))
    return rows


def fetch_immich_countries() -> list[str]:
    base = os.environ.get("IMMICH_BASE_URL", "").rstrip("/")
    api_key = os.environ.get("IMMICH_API_KEY", "")
    if not base or not api_key:
        return []

    url = f"{base}/api/search/explore"
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "immich-apps-country-lookup/1.0",
            "x-api-key": api_key,
            "Accept": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            payload = json.load(resp)
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
        print(f"WARN: Immich explore fetch failed: {exc}", file=sys.stderr)
        return []

    countries: set[str] = set()
    for section in payload if isinstance(payload, list) else []:
        field = section.get("fieldName") if isinstance(section, dict) else None
        if field not in ("exifInfo.country", "country"):
            continue
        for item in section.get("items") or []:
            value = item.get("value") if isinstance(item, dict) else None
            if isinstance(value, str) and value.strip():
                countries.add(value.strip())
    return sorted(countries)


def emit_ts(rows: list[tuple[str, str]]) -> None:
    lines = [
        "/* cspell:disable-file */",
        "/** Auto-generated by scripts/generate-country-lookup.py — do not edit. */",
        "export const GENERATED_COUNTRY_LOOKUP: Array<[RegExp, string]> = [",
    ]
    for zh_name, immich_name in rows:
        pattern = escape_regex(zh_name)
        lines.append(f'  [/{pattern}/, "{immich_name}"],')
    lines.append("];")
    lines.append("")
    OUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_TS} ({len(rows)} entries)")


def emit_aliases(countries: list[str]) -> None:
    if not countries:
        return
    OUT_ALIASES.write_text(
        json.dumps({"countries": countries}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT_ALIASES} ({len(countries)} Immich countries)")


def main() -> int:
    try:
        rows = territory_entries()
    except (urllib.error.URLError, TimeoutError, KeyError, json.JSONDecodeError) as exc:
        print(f"ERROR: CLDR fetch failed: {exc}", file=sys.stderr)
        return 1

    emit_ts(rows)
    countries = fetch_immich_countries()
    emit_aliases(countries)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
