{{- if .Values.onepassword.enabled }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "immich-line-bot.lineBotSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "immich-line-bot.labels" . | nindent 4 }}
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: {{ required "onepassword.lineBotItemPath required" .Values.onepassword.lineBotItemPath | quote }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "immich-line-bot.immichApiSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "immich-line-bot.labels" . | nindent 4 }}
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: {{ required "onepassword.immichApiItemPath required" .Values.onepassword.immichApiItemPath | quote }}
{{- end }}
