#!/usr/bin/env bash
# 從 1Password 寫入本機憑證檔（LaunchAgent 用，避免每次 sync 都跳 1Password 授權）
#
# 用法（只需執行一次，或 API key 輪換後）:
#   ./scripts/photo-sync/bootstrap-credentials.sh
#
# 產出: ~/.config/immich-apps/photo-sync.env (chmod 600)
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$HOME/.config/immich-apps/photo-sync.env"

if ! command -v op >/dev/null 2>&1; then
  echo "ERROR: op CLI not found" >&2
  exit 1
fi

eval "$("$ROOT/scripts/dev/load-env-from-op.sh")"

mkdir -p "$(dirname "$OUT")"
umask 077
cat > "$OUT" <<EOF
# Generated by bootstrap-credentials.sh — do not commit
IMMICH_INSTANCE_URL=${IMMICH_INSTANCE_URL:-https://immich.3q.fi}
IMMICH_API_KEY=${IMMICH_API_KEY}
EOF

echo "Wrote $OUT (mode 600)"
echo "LaunchAgent / immich-sync 會優先讀此檔，減少 1Password 彈窗。"
